### Counting the number of unique values in each row of a numpy array

In [14]:
import numpy as np

arr1 = np.random.seed(2)
arr = np.random.randint(0,10,size=(9,12))

print(arr1)
print(arr)

for i in range(9):
    unique = len(set(arr[i]))
    print("There are %d unique items in row %d" % (unique, i))


None
[[8 8 6 2 8 7 2 1 5 4 4 5]
 [7 3 6 4 3 7 6 1 3 5 8 4]
 [6 3 9 2 0 4 2 4 1 7 8 2]
 [9 8 7 1 6 8 5 9 9 9 3 0]
 [0 2 8 8 2 9 6 5 6 6 6 3]
 [8 2 1 4 8 1 6 9 5 1 2 4]
 [7 6 4 5 8 3 0 0 5 7 5 0]
 [8 6 5 1 7 4 3 6 1 4 0 8]
 [5 4 2 9 7 1 9 2 1 0 7 1]]
There are 7 unique items in row 0
There are 7 unique items in row 1
There are 9 unique items in row 2
There are 8 unique items in row 3
There are 7 unique items in row 4
There are 7 unique items in row 5
There are 7 unique items in row 6
There are 8 unique items in row 7
There are 7 unique items in row 8


### Checkerboard arrays

- Create a numpy array of dimension (20, 20) and fill it with a checkerboard pattern of 1's and 0's
- Can you do the same for a 3D array of dimension (20, 20, 20)
- What about an array of dimension (20, 40, 10)

In [22]:
zero_one = ([0,1])
checkerboard = np.resize(zero_one, (20))
print(np.abs(checkerboard - np.array([checkerboard]).T))

[[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]]


### Broadcasting

- Create a random matrix of binary values (0, 1)
- Create a vector with as many rows as the matrix containing random positive integers between 1 and 5
- Add the vector to every column using broadcasting
- Create a new matrix by multiplying the columns of the original by the vector
- Create a new matrix by multiplying every element by a scalar value

In [53]:
binary_m = np.random.randint(0, 2, size = (10,10), dtype = 'int64')
rand_m = np.random.randint(1, 6, size = (10,1), dtype = 'int64')

binary_m + rand_m
mult_m = binary_m * rand_m
mult_m * 3


array([[15,  0,  0,  0, 15,  0, 15, 15, 15,  0],
       [ 0,  0,  9,  0,  0,  9,  0,  9,  0,  0],
       [15, 15, 15,  0,  0, 15,  0,  0, 15, 15],
       [ 0,  0,  9,  9,  9,  9,  9,  9,  9,  0],
       [ 0,  9,  9,  9,  0,  0,  9,  9,  9,  0],
       [ 0,  0,  0, 15,  0, 15,  0, 15,  0, 15],
       [ 9,  0,  0,  0,  0,  0,  9,  0,  9,  9],
       [ 3,  3,  0,  3,  0,  0,  0,  3,  3,  3],
       [ 0,  0,  0,  9,  0,  0,  9,  0,  0,  9],
       [ 0,  3,  0,  0,  0,  3,  0,  3,  3,  0]], dtype=int64)

### Fancy Indexing

- Look at the numpy docs to explore all the ways which you can use numpy to generate tensors/matrices/arrays of random numbers
- Create a matrix of random numbers with 4 rows and 6 columns
- Index the element on the 3rd row, 2nd col
- Index all of the even rows
- Index all of the elements on even rows and odd columns
- Index the elements along the diagonal

In [83]:
random_m = np.random.randn(4,6)
random_m[3,4]

n_rows, n_columns = np.shape(random_m)

for i in range(0, n_rows):
    if i % 2 == 1:
        print(random_m[i])

for i, j in range(0, n_rows), range(0, n_columns):
    if i % 2 == 1 and j % 2 == 0:
        print(random_m[i,j])

[ 0.64125771  1.37630666  0.42428209 -0.44531792  0.84724506  0.84932209]
[-0.6742687  -2.30813991  1.05826214 -0.06561174  0.30397088 -0.10143653]


ValueError: too many values to unpack (expected 2)